authentication/from_scratch/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'register', to: 'users#new'
  get 'articles/new' => 'articles#new', :as => 'new_article'
  get 'articles/:id/destroy' => 'articles#destroy', :as => 'destroy_article'
  get 'users/new'
  # root 'users#new'
  root 'articles#index'

  resources :users
  resources :sessions
  resources :articles do
    resources :comments
  end
end

authentication/from_scratch/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

authentication/from_scratch/app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  include Visible

  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

authentication/from_scratch/app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Visible

  belongs_to :article
  belongs_to :user
end

authentication/from_scratch/app/models/concerns/visible.rb
# frozen_string_literal: true

module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived].freeze

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

authentication/from_scratch/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :password
  has_many :articles

  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    return unless user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)

    user
  end

  private

  def encrypt_password
    return unless password.present?

    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

authentication/from_scratch/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # handle new article
end

authentication/from_scratch/app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

authentication/from_scratch/app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_article
  before_action :set_comment, only: %i[destroy]

  def create
    @comment = @article.comments.create(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to article_path(@article), notice: 'Comment was successfully created.'
    else
      redirect_to article_path(@article), alert: 'Error creating comment.'
    end
  end

  def destroy
    @comment.destroy
    redirect_to article_path(@article), status: :see_other, notice: 'Comment was successfully deleted.'
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def set_comment
    @comment = @article.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

authentication/from_scratch/app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

authentication/from_scratch/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Signed up and logged in!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

authentication/from_scratch/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
    def destroy_link(resource)
        link_to "delete", resource, data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        }
    end
end

authentication/from_scratch/app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

authentication/from_scratch/app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

authentication/from_scratch/app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

authentication/from_scratch/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

authentication/from_scratch/app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
      <%= form.label :status %><br>
      <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

authentication/from_scratch/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

authentication/from_scratch/app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

authentication/from_scratch/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

authentication/from_scratch/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <% if current_user == @article.user%>
    <li><%= link_to "edit article", edit_article_path(@article) %></li>
    <li><%= destroy_link(@article) %></li>
  <% end %>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

authentication/from_scratch/app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <% if current_user == comment.user%>
    <p><%= destroy_link([comment.article, comment]) %></p>
  <% end %>

  <div>------</div>

<% end %>

authentication/from_scratch/app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
  <p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

authentication/from_scratch/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <header>
    <h1>Blog</h1>
    <nav>
      <inline> 
        <h3>
          <i><%= link_to "Home", root_url %></li> •︎
          <i><%= link_to "New Article", current_user ? new_article_path : login_path %></li>
        </h3>
      </inline>
    </nav>

    <div id="user_nav">
      <% if current_user %>
      <i>
          Logged in as <%= current_user.email %>
          <%= link_to "Logout", logout_path, method: :delete %>
        </i>
      <% else %>
        <%= link_to "Sign up", register_path %> or <%= link_to "Login", login_path %>
      <% end %>
    </div>
  </header>

  <body>
    <% flash.each do | name, msg | %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

authentication/from_scratch/app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <% if @user.errors.any? %>
    <div class="error_messages">  
      <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </p>
  <p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

authentication/from_scratch/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render "form", user: @user %>